name: tatc_env
channels:
  - conda-forge
  - default
dependencies:
  - python=3.8.10
  - geopandas=0.9.0
  - numba=0.53.1
  - pip=21.1.2
  - pydantic=1.8.2
  - pip:
    - sgp4==2.17
    - skyfield==1.37
