name: tatc_env
channels:
  - conda-forge
dependencies:
  - contextily = 1.2
  - geopandas = 0.12
  - ipykernel = 6.22
  - numba
  - numpy
  - pandas
  - pydantic = 1.10
  - shapely = 2.0
  - skyfield >= 1.41
  - sgp4
  - pip = 23
