name: tatc_env
channels:
  - conda-forge
dependencies:
  - python
  - geopandas
  - numba
  - numpy
  - pandas
  - pydantic
  - pyproj
  - shapely
  - skyfield
  - sgp4
  - pip>=20.1
  - pip:
    - autodoc_pydantic
    - black[jupyter]
    - coverage
    - sphinx
    - sphinx-rtd-theme
    - nbsphinx
