name: tatc_env
channels:
  - conda-forge
dependencies:
  - python
  - geopandas=0.10.2
  - numba=0.55.1
  - numpy==1.21.6
  - pandas=1.4.2
  - pydantic=1.9.1
  - pyproj=3.3.1
  - shapely=1.8.2
  - skyfield=1.41
  - sgp4=2.21
