name: tatc_env
channels:
  - conda-forge
dependencies:
  - python
  - geopandas>=0.10
  - numba
  - numpy
  - pandas
  - pandoc
  - pydantic
  - pyproj
  - shapely
  - skyfield
  - sgp4
  - pip>=20.1
  - pip:
    - autodoc_pydantic
    - black[jupyter]
    - coverage
    - myst-parser
    - nbsphinx
    - pylint-pydantic
    - sphinx
    - sphinx-rtd-theme
