name: tatc_env
channels:
  - conda-forge
dependencies:
  - python >=3.8,<3.11
  - geopandas = 0.12
  - numba
  - numpy
  - pandas
  - pydantic = 1.10
  - shapely = 2.0
  - skyfield >= 1.41
  - sgp4
  - pip = 23
