name: tatc_env
channels:
  - conda-forge
dependencies:
  - python=3.8.10
  - cartopy=0.18.0
  - geopandas=0.9.0
  - geoplot=0.4.3
  - numba=0.53.1
  - numpy=1.21.1
  - pandas=1.3.1
  - pip=21.1.2
  - pydantic=1.8.2
  - pyproj=3.1.0
  - shapely=1.7.1
  - pip:
    - sgp4==2.17
    - skyfield==1.37
